# BlueMapOfflineSkinSupport configuration file
#
# webroot
#     Set this to match the webroot value found in render.conf
#     The default value for BlueMap is "bluemap/web"
#
# alwaysUseSkinsRestorerForSkinLookup
# alwaysUseCustomSkinsManagerForSkinLookup
#     Enable these options if you want to always rely on SkinsRestorer / CustomSkinsManager to provide players' skins.
#     This will make it so that BlueMapOfflineSkinSupport will never use Mojang's native API to look up skins.
#
# prefsRevision
#     Do not change this value.

webroot: bluemap/web

alwaysUseSkinsRestorerForSkinLookup: false
alwaysUseCustomSkinsManagerForSkinLookup: false

prefsRevision: 1